{
 "title": "Fusion Dashboard Main",
 "description": "Craftana Dashboard for https://github.com/hexxone/cc-fusionmon",
 "tags": [ "minecraft" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "dataSource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Tritium Plant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Water Input",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "targets": [
    { "expr": "minecraft_tritium_water", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Water Heating Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "minecraft_tritium_water_heating_temperature",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Brine Production",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "minecraft_tritium_brine_production",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Brine Buffer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "targets": [
    { "expr": "minecraft_tritium_brine", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Brine Heating Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "minecraft_tritium_brine_heating_temperature",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Lithium Production",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "minecraft_tritium_brine_production",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Lithium Buffer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "targets": [
    { "expr": "minecraft_tritium_lithium", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Tritium Production",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "expr": "minecraft_tritium_tritium_production",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Reactor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Tritium Buffer",
   "type": "timeseries",
   "description": "buckets",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "targets": [
    { "expr": "minecraft_buffer_tritium", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Deuterium Buffer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "targets": [
    { "expr": "minecraft_buffer_deuterium", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Reactor Water",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "targets": [
    { "expr": "minecraft_fusion_water", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Injection Rate",
   "type": "gauge",
   "description": "milliBuckets per Tick",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mB/t" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_fusion_injection_rate * 1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "D-T Fuel",
   "type": "gauge",
   "description": "milliBuckets per Tick",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mB/t" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_fusion_d_t_fuel * 1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg Production Delta",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mB/t" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(minecraft_tritium_brine_production)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg(minecraft_tritium_lithium_production)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg(minecraft_tritium_tritium_production)",
     "legendFormat": "{{name}}"
    },
    { "expression": "$FINJ + $DTINJ", "type": "math" }
   ]
  },
  {
   "title": "Injection-Production Delta",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "minecraft_tritium_brine_production",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "minecraft_tritium_lithium_production",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "minecraft_tritium_tritium_production",
     "legendFormat": "{{name}}"
    },
    { "expression": "$FINJ + $DTINJ", "type": "math" }
   ]
  },
  {
   "title": "Plasma & Casing Temp",
   "type": "timeseries",
   "description": "Giga Celsius",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "minecraft_fusion_plasma_temperature / 1000000000",
     "legendFormat": "{{name}} in {{legend}}"
    },
    {
     "expr": "minecraft_fusion_case_temperature / 1000000000",
     "legendFormat": "{{name}} in {{legend}}"
    }
   ]
  },
  {
   "title": "Steam Production",
   "type": "timeseries",
   "description": "Thousand Buckets per Tick",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "minecraft_fusion_steam_production",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Steam Buffer",
   "type": "timeseries",
   "description": "Thousand Buckets",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "targets": [
    { "expr": "minecraft_fusion_steam / 1000", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Energy Buffer",
   "type": "timeseries",
   "description": "Million Forge Energy",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "minecraft_fusion_energy / 1000000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Turbine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Steam Flow Rate",
   "type": "timeseries",
   "description": "Kilobuckets per Tick",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "minecraft_turbine_steam_flow_rate/1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Steam Buffer",
   "type": "timeseries",
   "description": "Thousand Buckets",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "targets": [
    { "expr": "minecraft_turbine_steam / 1000", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Energy Production",
   "type": "timeseries",
   "description": "Million Forge Energy per Tick",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "minecraft_turbine_energy_production / 1000000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Energy Buffer",
   "type": "timeseries",
   "description": "Giga Forge Energy",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "minecraft_turbine_energy / 1073741824",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}